[package]
name = "atomiclock_async"
version = "0.1.0"
edition = "2021"

[dependencies]
atomiclock = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/atomiclock.git"}
wakelist = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/wakelist.git"}
logwise = "~0"